name: Poricom Linux (deb) Package

on: [push]

jobs:
  Build-Deb:
    runs-on: "ubuntu-latest"
    env:
      DISPLAY: ':99.0'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: poricom-py39
          use-mamba: true

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{hashFiles('environment/base.yaml') }}-${{hashFiles('environment/build.yaml') }}-${{ env.CACHE_NUMBER}}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          mamba env update -n poricom-py39 -f environment/base.yaml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Update environment
        run:
          mamba env update -n poricom-py39 -f environment/build.yaml
        if: steps.cache.outputs.cache-hit != 'true'

